### ISSUE TITLE
Training ASR with this model for another language

### ISSUE THREAD

**Issue by EmreOzkose** [csukuangfj/icefall-asr-conformer-ctc-bpe-500#1]
Hi, thank you for sharing a pre-trained model. 

Have you ever tried to use this pre-trained model for training of another language ASR? Do you think that it will be useful for training ASR with another language? 

Of course, "lang_bpe" will be also changed.

Note: I will also so experiments with this setup and report results here.

**Comment by csukuangfj** [comment]
No, I have not used this pre-trained model for other languages. Not sure whether it is helpful or not.

There are recipes for other languages, instead of English, in icefall that uses similar model architectures.
For instance, there is an ongoing pull request for the AIShell dataset, which is Chinese. Please see
https://github.com/k2-fsa/icefall/pull/30

**Comment by EmreOzkose** [comment]
I started a training with pre-trained model on another language (Turkish data), however the beginning of the training ( a few epoch) is nearly same with "from scratch trainings". I checked if parameters are changed after loading model, and they are changed. I guess that there will not be big difference with pre-trained model.

**Comment by EmreOzkose** [comment]
I have 100h Turkish data for training and 1h data for test. I did some experiments with pre-trained model and got 0,62 relative improvement with pre-trained model. Certainly starting with pre-trained model works !
